CREATE TABLE producto (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sku VARCHAR(50) NOT NULL,
    categoria VARCHAR(80) NOT NULL,
    marca VARCHAR(80) NOT NULL,
    modelo VARCHAR(120) NOT NULL,
    especificacion VARCHAR(500) NOT NULL,
    critico BOOLEAN NOT NULL DEFAULT FALSE,
    activo BOOLEAN NOT NULL DEFAULT TRUE,

    CONSTRAINT uk_producto_sku UNIQUE (sku),
    CONSTRAINT ck_producto_sku CHECK (
        sku = UPPER(BTRIM(sku)) AND sku <> ''
    ),
    CONSTRAINT ck_producto_categoria CHECK (BTRIM(categoria) <> ''),
    CONSTRAINT ck_producto_marca CHECK (BTRIM(marca) <> ''),
    CONSTRAINT ck_producto_modelo CHECK (BTRIM(modelo) <> ''),
    CONSTRAINT ck_producto_especificacion CHECK (
        BTRIM(especificacion) <> ''
    )
);