CREATE TABLE almacen (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo VARCHAR(30) NOT NULL,
    nombre VARCHAR(120) NOT NULL,
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT uk_almacen_codigo UNIQUE (codigo),
    CONSTRAINT ck_almacen_codigo CHECK (codigo = UPPER(BTRIM(codigo)) AND codigo <> ''),
    CONSTRAINT ck_almacen_nombre CHECK (BTRIM(nombre) <> '')
);

-- Datos iniciales del escenario simulado descrito en el informe.
INSERT INTO almacen (codigo, nombre) VALUES
    ('A01', 'Tienda principal'), ('A02', 'Depósito'), ('A03', 'Despacho');

CREATE TABLE politica_stock (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    producto_id BIGINT NOT NULL REFERENCES producto(id),
    almacen_id BIGINT NOT NULL REFERENCES almacen(id),
    minimo BIGINT NOT NULL,
    maximo BIGINT NOT NULL,
    CONSTRAINT uk_politica_producto_almacen UNIQUE (producto_id, almacen_id),
    CONSTRAINT ck_politica_limites CHECK (minimo >= 0 AND maximo > minimo)
);
