spring.application.name=stockguard


# Hibernate comprueba el esquema sin modificarlo
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false

# Migraciones con Flyway
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.default-schema=public

spring.config.import=optional:file:./application-local.properties



